### ISSUE TITLE
Respond to reviews

### ISSUE THREAD

**Issue by bc** [bc/jnp2017#1]
concerns about the interpretation and presentation of the findings. 
Respond to all critiques raised by the reviewers. 
Make sure to address all the concerns point by point.

1) indicate the previous manuscript number in your cover letter to the editor.
2) attach a point-by-point response to the previous referee comments as supporting material (as a separate file from the cover letter).

- [x] # Reviewer #1 (Comments to the Author (Required)):

> Here the authors present work on the feasible activations of force production and how it relates to neuromuscular control. In a clear presentation they describe how, for a fixed orientation and constant desired force output, the musculo-skeletal system necessarily restricts the admissible muscle activations. This set of all feasible activations forms a low-dimensional volume, or polytope, in the ambient higher dimensional space of muscle activations. The authors then argue that this constrained set of muscle activations reconciles the three dominant approaches to sensorimotor control: muscle synergies, Bayesian techniques and fitness/cost functions, which they describe as being in competition. The manuscript is interesting and well written, but I take issue with many of the basic concepts proposed.

>In part because of the topic, this does not come across as a research paper but rather an opinion piece to support the author's feasibility theory. It is not clear what the novel contribution is other than the analyses they present which are designed to bolster their arguments for the feasibility theory. As explained below, however, it is also not clear why this is actually an organizing theory, rather than a very well articulated description of physiological constraints, which although often given little consideration, are usually addressed.

> These issues aside, I am not convinced that this work reconciles what the authors describe as the three main approaches to sensorimotor control. In fact, I don't believe these three approaches are in competition. Muscle synergies, despite various interpretations, are often are thought to reflect the nervous system's attempt to simplify movement by reducing the number of controlled variables. The Bayesian approach is used to examine beliefs and estimates for the control problem under conditions of noise and uncertainty. Fitness landscapes, (via optimal control) are employed to examine how the nervous system organizes control and quantifies "goodness" among its many (feasible) options. The set of feasible activations is a constraint on potential commands, which all three approaches must contend with. None of these ideas is necessarily in competition, and they are often combined in sensorimotor control studies.

> It was not at all obvious how this approach explains or reconciles the effort to use cost functions to understand neuromuscular control. Strangely this explanation was not presented in the manuscript's results either. In the Discussion the authors describe optimization as an iterative search in the dark, whereas enumerating the feasible activation space is akin to turning on the lights. I think they are confusing the goal of optimal control with the algorithm. But more importantly, as their work makes plain, merely visualizing the feasible activation space is difficult. Making sense of it in the context of motor control (especially for something more difficult than static force production) might prove just as difficult.

>Regarding the Bayesian approach I was especially confused. To begin with, I disagree that the references cited argue for a probabilistic representation of muscle activations or priors over commands. They in fact present an approach for how commands are chosen, deterministically, based on beliefs in uncertain or random variables. While commands are certainly modeled as being corrupted by noise, they are not treated as random variables themselves. More importantly, identifying the space of all possible muscle activations is very different from the probability of muscle activations. Yet the authors repeatedly imply they have identified the pdf's of muscle activation. Even if we were to side-step these issues, the author's interpretation of muscle pdf's implies that the noise and variability in commands would be due to "bouncing around" in the polytope. This would necessarily imply that muscle commands were highly correlated whereas I am under the impression experimentally observed variability does not have this kind of structure and is largely uncorrelated.

>With regard to the third approach, muscle synergies, here I am very sympathetic to the author's arguments and think this is their strongest case. It seems very sensible that synergies may merely reflect the constraints of the feasible activations, yet they have presented this in prior published work.

some other minor points:

>I don't see how the parallel coordinates reveal the structure of the feasible space. It depicts the range of possible values, but it is difficult to see the structure.

>Finally, the authors tacitly assume without much discussion that muscle forces are merely a linear scaling of activation, which is clearly not the case. Also, all analyses are done for static force production. I assume both of these choices were made to simplify the computations, but how much more difficult would these analyses be if you modeled force production as a nonlinear process? And what does this say about the approach in general if one wishes to use it in a more realistic setting and with non-static conditions?

- [x] # Reviewer #2 (Comments to the Author (Required)):

## General Comments
This manuscript presents a new technique for the analysis of multiple muscle activations during the application of static contact forces. The key idea, promoted by the senior author in a number of other studies, is that the constraints established by the mechanics of the musculoskeletal apparatus and by the motor task establish a set of "feasible muscle activations" whose structure is essential to understand the mechanisms of coordination from different computational perspectives. In a way, the authors are restating the importance of the structure of the domain for the understanding of a function. While this is an almost self-evident concept, a good deal of models for neural control tend to focus on neural activities, neglecting the structure of these constraints. The manuscript also illustrates the application of some techniques for providing a simple graphical approach to the inspection of the feasible space. I think that this is a generally sound and well written manuscript. I am not convinced however that what is presented here is a "theory" but rather an analytical technique based on concepts that are not controversial. While the general concepts may have a large domain of applicability, those describe here (Equations 1 to 9) are strictly limited to the application of static contact forces at a fixed configuration of the limb, which can be treated linearly. The paper would benefit from a more extended discussion of the problems to be expected in extending the use of these techniques to dynamical conditions. This seems particularly essential if the authors intend to promote the approach to the broader domain of motor control.

## Specific comments

>Abstract. While the approach presents a common ground for different approaches (synergies, Bayesian models, optimal control), it does not really "unify" them. Or at least no such unification is offered by the work presented here. So, this seems an excessive claim. It is more plausible to state that any theory of motor control should consider the limits established by the feasible structure of the domain, as described here.

>Page 4. The dependence of the endpoint force upon the activation is valid (within bounds) only under static conditions and at a fixed configuration. These apply to the particular case discussed in this work.

>Under what conditions can one assume that the feasible set (not really a "space" in a strict sense) is convex? I have the impression that fixed neural constraints between the muscle activations could lead to non-convexity. Could the authors say something about this?

>Page 6, toward the bottom. Reference to "four vertical lines" applies to Figures 3 and 4. In Figure 2 there are only 3 lines for 3 cost functions.

>PCA. The use of PCA for characterizing the geometry of the feasible space and how it changes under different conditions is appropriate. However, I would consider it neither a way to describe muscle synergies (because of the orthonormality constraints) nor for dimensionality reduction in nonlinear cases, where PCA tends
to over-estimate the real dimensionality of the underlying manifold.

>Page 9. There is a typo toward the end of the first paragraph in the description of the muscle pairs.

>Figure 3. The grey lines connecting the last muscle in the list with the first cost function do not carry any meaning and could be removed.

>The use of color in the figures does not seem to be scientifically necessary.

- [x] # Reviewer #3 (Comments to the Author (Required)):

> The authors make compelling argument to use a novel computational approach, feasibility theory, to calculate all possible neuromechanical activation combinations that allow a task to be completed successfully. The manuscript applies this theory to a finger model with 7-muscles where the goal is to produce a force from 0-100% MVC in the distal direction. I am enthusiastic about the manuscript, however I believe a few things need clarification to generalize to the wider neurophysiology audience.

>1) While the histograms for the finger force task provided strong evidence that feasibility theory may be accurate, the manuscript could use more information on exactly how to apply this to experimental studies. For example, if a researcher hopes to use feasibility theory to explain a movement, where would they begin? I imagine you begin with a mathematical model (e.g. the geometric model of the motion) and EMG patterns, but then do you estimate the feasibility space with the Hit-and-Run algorithm? I think a paragraph in the discussion of how this may be applied to a novel task would allow this article to impact more readers.

>2) Do anthropometric differences need to be incorporated into this model? For example, if feasibility theory were to be applied to low limb force production, would differences in varus/valgus angle of the knee affect the feasible activation space for production of forces at the knee or foot since the lever arms for each muscle change? In this way, how does feasibility theory generalize to individuals with varying anthropomorphism?

>3) Page 4, lines 6 & 7, muscle activation patterns are between 0 and 1, but what happens in the case of lengthening (or eccentric) contractions? Is this still weighted between 0 and 1 even though the muscle may be resisting a movement?

>4) The text on page 6, first paragraph, under "Analysis of feasible activation spaces" describing figure 2 is confusing.
It begins by saying "We begin by drawing n parallel vertical lines... with the axes of each line set between 0 and 1, each point (figure 2a)..." Does this refer to the cube in figure 2a that contains the polygon of feasible activation spaces or the 3 vertical lines in fig 2b?

>Further, you "connect their coordinates by n - 1 lines as shown in figure 2b." But in figure 2b, you connect the three vertical lines with n + 1 (4, in this case) lines in figure 4b.

>Lastly, in lines 34-35 (page 6), you "simple add four vertical lines at the far right of the parallel coordinates plot, one for each cost function fig 2c." Figure 2c shows three vertical lines (which appear to be cost functions) connected by four co-varying linear constraints, but I am unclear.

>5) Page 6: what does 'neural effort' mean? Is this a proxy for the amplitude of the input signal to the motor neurons innervating these muscles?

>6) Page 9(minor), line 11: the formatting of the muscle pairs did not come out readable when downloading the manuscript as a pdf.

7) Page 11, lines 3-5, you state "feasible activation spaces are, in fact, the high-dimensional landscapes upon which all neuromuscular learning..., must occur." But this has only been validated in a model for a static fingertip force task. This would be more appropriate if experimental data outside of the model conformed to the feasible activation space.

>8) Page 11 last line delete second 'and' between the words: "soft and constraints."

>9) Page 4 (minor): line 27, "... limb models have over 40 muscles such as (references)." It would be helpful to list these limbs rather than just the references.

>10) Regarding the dimensionality reduction, the muscle loadings would not flip sign (Figure 6) if a non-negative matrix factorization had been used in place of a PCA. NMF is more sensitive to individual muscle loadings (e.g., Tresch et al., Matrix factorization algorithms for the identification of muscle synergies: evaluation on simulated and experimental data sets. J Neurophysiol. 2006) and more robust across EMG signals with signal dependent noise. PCA is generally outperformed by NMF, ICA, or even PCA with a varimax rotation when trying to 'reverse engineer' and solve for computationally created muscle synergies. I do not believe you need to change your analysis to an NMF, but the limitation of PCA should be noted when discussing the limitations of dimensionality reduction techniques given experimentally plausible sample sizes. PCA is the least robust of the factorization algorithms.

**Comment by bc** [comment]
intro gap statement altered to focus on how the theories are non complementary, rather than in-competition
```
%the gap
Current theories of neuromuscular control\footnote{Neuromuscular control is variously referred to as neural, motor, sensorimotor, etc. control.} are alternative responses to overcome the curse of dimensionality in this context. These alternative approaches, however, are seldom combined and often the insights from one realm are not readily applicable to the others. Here we emphasize how the mechanics of the body and the physics of the task constitute the common ground for all theories.```

**Comment by bc** [comment]
added description of the use case for parallel coordinates, and how it's most valuable as an interactive data visualization.
```
While it is challenging to understand the structure of the feasible activation space with a static plot of the parallel coordinates, interactively manipulating the muscle ranges on one or multiple axes makes it very easy to view and describe how muscle activations change in the face of different constraints.
```

**Comment by bc** [comment]
we suggest the reviewers manipulate and interact with the parallel coordinates plot: http://valerolab.org/supplemental_sites/jnp2017/

**Comment by bc** [comment]
Changed PDF to 'space upon which PDF is formed;
```The histogram heatmaps in Fig.~\ref{fig:figure_6_histogram_heatmap} illustrate the changes and shrinking of within-muscle histograms (the space upon which probability density functions must operate) of valid activation levels across task intensities, converging to a single solution at maximal force output.```

**Comment by bc** [comment]
included brief discussion of dynamics 

```\subsection*{Extension to dynamical force production or movement}
Limbs are valuable for more than just their ability to produce isometric forces. First, there is the extension to 'non-static isometric' force production (force production of a non-moving endpoint which includes variation over time), which incorporates the dynamics between the muscle forces at the tendon insertion point and the endpoint's resultant wrench. As muscles exhibit state dependence, the ability for an animal to produce precise forces is affected by the tendon tensions from moment to moment. The inter-muscle dynamics across a human index finger, for example, would necessarily require a feasible activation trajectory—--which may or may not be representable by a convex hull. Applying Feasibility Theory to non-static isometric force production will require detailled investigation into the dynamics of musculoskeletal force transduction.
With changes in the moment arms from posture to posture, movement studies incorporating Feasibility Theory must contend with the dynamics mentioned above, as well as the dynamics of posture dependence (to define tendon leverage across joints) and muscle force-length relationships (to define muscle capability). Movement studies and motion-to-force transitions may offer opportunities in ```

**Comment by bc** [comment]
extended to talk about motion and convexity
```\subsection*{Extension to dynamical force production or movement}
Limbs are valuable for more than just their ability to produce isometric forces. First, there is the extension to 'non-static isometric' force production (force production of a non-moving endpoint which includes variation over time), which incorporates the dynamics between the muscle forces at the tendon insertion point and the endpoint's resultant wrench. As muscles exhibit state dependence, the ability for an animal to produce precise forces is affected by the tendon tensions from moment to moment. The inter-muscle dynamics across a human index finger, for example, would necessarily require a feasible activation trajectory---which may or may not be representable by a convex hull. Applying Feasibility Theory to non-static isometric force production will require detailed investigation into the dynamics of musculoskeletal force transduction.
Extension to movement is nontrivial: with changes in the moment arms from posture to posture, movement studies incorporating Feasibility Theory must contend with the dynamics mentioned above, as well as the dynamics of posture dependence (to define tendon leverage across joints) and the muscle force-length relationship (to define muscle capability). For studies of movement and movement-to-force transitions, a more precise definition of feasibility may advance the explanatory capability of motor control models.```

**Comment by bc** [comment]
wrote about how to apply Feasibility Theory in experiments:
```
\subsection*{How to apply Feasibility Theory in an experiment}
The most important input to this analysis is the relationship between muscles and the endpoint wrench. With this relationship composed as the $H$ matrix as in \ref{eq:constraints}, and a desired wrench $w$, Hit-and-Run can be used to produce parallel coordinate plots and density histograms. For example, using a measure of muscle activation (such as fine-wire EMG), an experimentalist can compare the muscle activation pattern chosen by a research participant in comparison to the full distribution of feasible activations that could achieve the same force, and see how those patterns change across fatigue, disability of a muscle, or manipulation of the feedback.```

**Comment by bc** [comment]
To clarify what we mean by "activation" I added this sentence that clarifies that it's a muscle-independent model. Just tendon-tension to endpoint force.
``` We do not differentiate between concentric or eccentric contraction---we define muscle activation as the net static tendon tension, normalized by the maximum tendon tension possible by that muscle.```

**Comment by bc** [comment]
Clarified what 'neural effort' means in our context of the cost functions:
``` The cost functions are defined at the level of neural effort ($L_1$, and $L_2$ norms, representing the normalized sum of descending neural $\alpha$-drive); and at the level of metabolic cost, thought to be approximated by neural drive weighted by the strength of each muscle ($L_1^w$ and $L_2^w$ norms)~\cite{Prilutsky2000Muscle,crowninshield1981physiologically}.```

**Comment by bc** [comment]
improved ^^
```The cost functions are defined at the level of neural effort ($L_1$, and $L_2$ norms, representing the normalized sum of descending neural $\alpha$-drive to the motor neuron pools); and at the level of metabolic cost, thought to be approximated by neural drive weighted by the strength of each muscle ($L_1^w$ and $L_2^w$ norms)~\cite{Prilutsky2000Muscle,crowninshield1981physiologically}.```

**Comment by bc** [comment]
mention NMF
```
PCA is not the only method used to extract lower-dimensional representations of motor patterns \cite{d2003combinations,ting2005limited}, and the other methods would likely yield different results. For example, Non-Negative Matrix Factorization (NMF)  would not be subject to the random flips in sign as seen in \ref{fig:pca_variance_explained} \cite{tresch2006matrix}. We acknowledge that alternative techniques of dimensionality reduction may have different results when applied to feasible activation space data. The bootstrapping technique for sensitivity analysis would be equally applicable to these techniques.
```
